server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CarbonApp
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  messages:
    basename: i18n/messages
    fallback-to-system-locale: false

jwt:
  secret: 546A576E5A7234753778214125442A472D4B6150645367566B58703273357638